import type { Metadata } from "next";
import {
  Poppins as FontPoppins,
  Open_Sans as OpenSans,
} from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import { io } from "socket.io-client";

const fontPoppins = FontPoppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const fontOpenSans = OpenSans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const URL = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:5000";
const socket = io(URL, { autoConnect: false });

socket.onAny((event, ...args) => {
  console.log(event, args);
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-open_sans ${fontPoppins.variable} ${fontOpenSans.variable}`}
      >
        <ToastContainer />
        <div className="min-h-screen bg-dark-blue">{children}</div>
      </body>
    </html>
  );
}
