import type { Metadata } from "next";
import {
  Poppins as FontPoppins,
  Open_Sans as OpenSans,
} from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import { SocketProvider } from "../components/SocketProvider";

const fontPoppins = FontPoppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const fontOpenSans = OpenSans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>
) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-open_sans ${fontPoppins.variable} ${fontOpenSans.variable}`}
      >
        <ToastContainer />
        <SocketProvider>
          <div className="min-h-screen bg-dark-blue">{props.children}</div>
        </SocketProvider>
      </body>
    </html>
  );
}
